name: Tests

on:
    push:
    pull_request:
    schedule:
        - cron: '00 09 * * 6'

jobs:
    tests:
        runs-on: ubuntu-latest
        env:
          PYTHONHASHSEED: 'apple'
        strategy:
          matrix:
            python-version: [ '3.7', '3.8', '3.9', '3.10', '3.11' ]
            os: ['ubuntu-latest']
        steps:
            - name: Clone and checkout branch
              uses: actions/checkout@v4

            - name: Set up Python ${{ matrix.python-version }} in ${{ matrix.os }} OS.
              uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python-version }}

            - name: Build project
              run: make

            - name: Run tests
              run: make test